#pragma once

#include <algorithm>
#include <array>
#include <assert.h>
#include <functional>
#include <iostream>
#include <memory>
#include <optional>
#include <span>
#include <sstream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include <deque>
#include <random>
#include <variant>
#include <filesystem>