#version 460
#include "Bindless.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

layout(push_constant) uniform PushConstants {
    uint imageIndex0;
    uint imageIndex1;
    uvec2 resolution;
};

void main() {
    ivec2 coord0 = ivec2(gl_GlobalInvocationID.xy);
    ivec2 coord1 = coord0 / ivec2(2); 
    
    if (coord0.x >= resolution.x || coord0.y >= resolution.y) {
        return;
    }

    vec2 uv = vec2(coord0) / vec2(resolution);
    
    imageStore(rgba8ImagesW[imageIndex0], coord0, vec4(1.f, 0.f, 0.0, 1.0));
    imageStore(rgba8ImagesW[imageIndex1], coord1, vec4(0.f, 1.f, 0.0, 1.0));
}
