#version 460
#include "Bindless.glsl"
#include "BRDF.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

layout(push_constant) uniform PushConstants {
    uint imageIndex0;
    uint imageIndex1;
    uvec2 resolution;
};

// directional albedo of specular BRDF with F set to 1
float RsF1(float r, float nDotL) {
    // assumed normal = vec3(0, 1, 0)
    vec3 lightDir = vec3(sqrt(1.f - nDotL * nDotL), nDotL, 0.f);

    float sum = 0.f;
    int nSamplesPerAxis = 256;
    for (int i = 0; i < nSamplesPerAxis; i++) {
        for (int j = 0; j < nSamplesPerAxis; j++) {
            float azimuth = ((float(j)) / float(nSamplesPerAxis)) * 2.f * PI;
            float cosTheta = ((float(i)) / float(nSamplesPerAxis));
            float sinTheta = sqrt(1.f - cosTheta * cosTheta);

            vec3 viewDir = vec3(sinTheta * cos(azimuth), cosTheta, sinTheta * sin(azimuth));
            float nDotV = viewDir.y;

            vec3 halfway = viewDir + lightDir;
            if (dot(halfway, halfway) < 1e-8) {
                continue;
            }
            halfway = normalize(halfway);

            float nDotH = halfway.y;
            float vDotH = dot(viewDir, halfway);

            float D = ggxNDF(r, nDotH);
            float G = ggxVisibility(r, nDotL, nDotV);
            float F = 1.f;

            float BRDF = D * G * F;
            sum += BRDF * nDotV;
        }
    }
    float normalizingFactor = (2.f * PI) / (float(nSamplesPerAxis) * float(nSamplesPerAxis));
    return sum * normalizingFactor;
}

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    
    if (coord.x >= resolution.x || coord.y >= resolution.y) {
        return;
    }

    float r = (float(coord.x) + 0.5f) / float(resolution.x);
    float nDotL = (float(coord.y) + 0.5f) / float(resolution.y);

    float radiosity = RsF1(r, nDotL);

    int nSamples = 256;
    float sum = 0.f;
    for (int i = 0; i < nSamples; i++) {
        float mu = (float(i) + 0.0001f) / float(nSamples);
        sum += RsF1(r, mu) * mu;
    }
    float barRsF1 = (2.f * sum) / float(nSamples);

    imageStore(rgba8ImagesW[imageIndex0], coord, vec4(radiosity, radiosity, radiosity, 1.0));
}
